name: InfinityStonesProtection
version: '${project.version}'
main: dev.snowz.infinitystonesprotection.InfinityStonesProtection
api-version: "1.20"
author: SnowzNZ
depend:
  - InfinityStones
  - CustomCrafting
