name: InfinityStonesProtection
version: '${project.version}'
main: dev.snowz.infinitystonesprotection.InfinityStonesProtection
author: SnowzNZ
description: Protect your Infinity Stones after crafting them!
website: https://github.com/SnowzNZ/InfinityStonesProtection
api-version: "1.20"
depend:
  - InfinityStones
  - CustomCrafting
commands:
  ispreload:
    description: Reload the config
    usage: /ispreload
    permission: isp.reload
permissions:
    isp.reload:
        description: Allows the player to reload the config
        default: op